# Generated by Django 2.0.7 on 2018-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Slow', 'Slow'), ('Movie Music', 'Movie Music'), ('Rap', 'Rap'), ('Pop', 'Pop'), ('Country', 'Country'), ('Oldies', 'Oldies'), ('Dance', 'Dance'), ('Rock', 'Rock')], default='Pop', max_length=25),
        ),
    ]
