# Generated by Django 2.0.7 on 2018-10-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Fast', 'Fast'), ('Slow', 'Slow'), ('Dance', 'Dance'), ('Other', 'Other')], default='Fast', max_length=25),
        ),
    ]
