# Generated by Django 2.0.7 on 2018-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_auto_20181026_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='on_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
