# Generated by Django 2.0.7 on 2018-10-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
