# Generated by Django 2.0.7 on 2018-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_auto_20181026_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
