# Generated by Django 2.0.7 on 2018-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_vote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
    ]
