# Generated by Django 2.0.7 on 2018-10-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_remove_vote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.CharField(default='Hoco2018', max_length=200),
        ),
    ]
