# Generated by Django 2.0.7 on 2018-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='winner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='winnerArtsit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
