# Generated by Django 2.0.7 on 2018-10-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_auto_20181026_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='winnerArtsit',
            new_name='winnerArtist',
        ),
    ]
