# Generated by Django 2.0.7 on 2018-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0013_auto_20181026_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='artist1',
            field=models.CharField(default='Artist1', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='artist2',
            field=models.CharField(default='Artist2', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='song1',
            field=models.CharField(default='Song1', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='song1Win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='song2',
            field=models.CharField(default='Song2', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='song2Win',
            field=models.BooleanField(default=False),
        ),
    ]
